export type UniversityCardData = {
  category: string;
  courses: string[];
  budget: number;
  universityName: string;
  rating: string;
  reviews: number;
  approvals: string;
  features: string[];
  imageUrl: string;
  logoUrl?: string;
  tag?: string;
  admissionClosing: string;
};

export const allUniversityCardsData: UniversityCardData[] = [
  {
    universityName: "Manipal Online University",
    courses: ["Operations", "MS.c"],
    rating: "4.6/5",
    reviews: 178,
    approvals: "AICTE | NAAC | NBA | QS | UGC",
    features: ["No-Cost EMI Available", "Flexible Payment Options"],
    imageUrl: "/images/cambridge.png",
    logoUrl: "/logo/Manipal.svg",
    tag: "Trending",
    budget: 10000,
    admissionClosing: "29 JULY",
    category: "UG Courses",
  },
  {
    universityName: "Jain Online University",
    courses: ["Operations", "MS.c"],
    rating: "4.5/5",
    reviews: 200,
    approvals: "UGC | DEB",
    features: ["Flexible Payment Options"],
    imageUrl: "/images/uni.png",
    logoUrl: "/logo/Manipal.svg",
    tag: "Top Rated by Students",
    budget: 10000,
    admissionClosing: "29 JULY",
    category: "UG Courses",
  },
  {
    universityName: "Amity Online University",
    courses: ["Operations", "MS.c"],
    rating: "4.7/5",
    reviews: 150,
    approvals: "AICTE | NIRF",
    features: ["No-Cost EMI Available"],
    imageUrl: "/images/cambridge.png",
    logoUrl: "/logo/Manipal.svg",
    budget: 10000,
    admissionClosing: "29 JULY",
    category: "UG Courses",
  },
  {
    universityName: "Lovely Professional University",
    courses: ["Operations", "MS.c"],
    rating: "4.4/5",
    reviews: 180,
    approvals: "UGC | WES",
    features: ["Scholarship Available"],
    imageUrl: "/images/uni.png",
    logoUrl: "/logo/Manipal.svg",
    tag: "Popular Choice",
    budget: 10000,
    admissionClosing: "29 JULY",
    category: "PG Courses",
  },
  {
    universityName: "Symbiosis Online",
    courses: ["Operations", "MS.c"],
    rating: "4.8/5",
    reviews: 220,
    approvals: "NAAC | DEB",
    features: ["Guaranteed Placement Assistance"],
    imageUrl: "/images/cambridge.png",
    logoUrl: "/logo/Manipal.svg",
    budget: 10000,
    admissionClosing: "29 JULY",
    category: "PG Courses",
  },
  {
    universityName: "IGNOU Online",
    courses: ["Operations", "MS.c"],
    rating: "4.3/5",
    reviews: 300,
    budget: 10000,
    approvals: "UGC | AICTE",
    features: ["Government Approved"],
    imageUrl: "/images/uni.png",
    logoUrl: "/logo/Manipal.svg",
    category: "PG Courses",
    admissionClosing: "29 JULY",
  },
  {
    universityName: "Bharati Vidyapeeth",
    courses: ["Operations", "Leadership"],
    rating: "4.2/5",
    reviews: 160,
    budget: 700000,
    approvals: "NIRF | NAAC",
    features: ["Modern Curriculum"],
    imageUrl: "/images/cambridge.png",
    logoUrl: "/logo/Manipal.svg",
    tag: "New Admission",
    admissionClosing: "29 JULY",
    category: "PG Courses",
  },
  {
    universityName: "Sikkim Manipal University",
    rating: "4.0/5",
    courses: ["Operations", "MS.c"],
    reviews: 190,
    budget: 10000,
    approvals: "DEB | UGC",
    features: ["Weekend Classes"],
    imageUrl: "/images/uni.png",
    logoUrl: "/logo/Manipal.svg",
    admissionClosing: "29 JULY",
    category: "Finance",
  },
  {
    universityName: "Chandigarh University",
    courses: ["Operations", "MS.c"],
    rating: "4.9/5",
    reviews: 250,
    approvals: "AICTE | QS",
    budget: 10000,
    features: ["Industry Ready Courses"],
    imageUrl: "/images/cambridge.png",
    logoUrl: "/logo/Manipal.svg",
    tag: "Highly Rated",
    admissionClosing: "29 JULY",
    category: "Finance",
  }, // Extra dummy cards for "View More"
  {
    universityName: "Example University 10",
    courses: ["Operations", "MS.c"],
    rating: "4.1/5",
    budget: 30000,
    reviews: 120,
    approvals: "UGC",
    features: ["Flexible Schedule"],
    imageUrl: "/images/uni.png",
    admissionClosing: "29 JULY",
    category: "Finance",
  },
  {
    universityName: "Example University 11",
    courses: ["Operations", "MS.c"],
    rating: "4.2/5",
    reviews: 130,
    budget: 100000,
    approvals: "NAAC",
    features: ["Online Library"],
    imageUrl: "/images/cambridge.png",
    admissionClosing: "29 JULY",
    category: "PG Courses",
  },
  {
    universityName: "Example University 12",
    rating: "4.3/5",
    courses: ["Operations", "MS.c"],
    reviews: 140,
    budget: 400000,
    approvals: "AICTE",
    features: ["Dedicated Mentors"],
    imageUrl: "/images/uni.png",
    admissionClosing: "29 JULY",
    category: "UG Courses",
  },
];
